index.js, lib/middleware/serveIndex.js, lib/server.js, package-lock.json, package.json, test/lib/server.js
@RandomByte @matz3 please take a look into the new serveIndex alternative for the ui5-server.
There are still some internals from the resource used when creating the resource info object. Maybe some of the internals can also become something for a more official API of the Resource but we could do that in a second step and provide the simplistic serveIndex to avoid the dependency to a github repo.
=> [FEATURE] simplistic serveIndex with additional properties

lib/middleware/serveIndex.js, test/lib/server.js
fixes #39
Signed-off-by: Michael Sprauer <Michael.Sprauer@sap.com>
=> skip empty resources and serve them as 404

.eslintrc.js, index.js, jsdoc.json, lib/middleware/discovery.js, lib/middleware/nonReadRequests.js, lib/middleware/serveIndex.js, lib/middleware/serveResources.js, lib/middleware/serveThemes.js, lib/middleware/versionInfo.js, lib/server.js, lib/sslUtil.js, package-lock.json, package.json
Also:
- prevent use of unkown tags
- add some docdash specific page options
=> [INTERNAL] JSDoc: Make API private by default

lib/middleware/csp.js, lib/server.js, test/lib/server/main.js, test/lib/server/middleware/csp.js
When option cspDefaults:true is given, the server now sends two policies
for *.html files, both in report-only mode:
- sap-target-level-1, which forbids inline scripts and only allows
sources from self
- sap-target-level-2, which additionally forbids 'eval'
Each policy is sent with its own 'Content-Security-Policy-Report-Only'
header. This might look uncommon, but simplifies automated validation of
the violation reports that are sent by the browser. Browsers don't
consistently report blocked-uri or source-file, but the original-policy
is reported consistently.
middleware/csp.js:
- allow to define and send a 2nd default policy
- skip execution for file types other than *.html and for HTTP methods
other than POST and GET
- use native capabilities of the express request object instead of …
=> [FEATURE] Add Server Option to Send SAP's Target CSPs by default

lib/middleware/csp.js, test/lib/server/middleware/csp.js
With change 4f059670306c97ab5f34d82bb335f5ee21d73c72, the CSP middleware
made use of 'express' APIs on the request object. When used in an
environment without 'express' (e.g. the OpenUI5 legacy grunt tooling),
the CSP middleware failed for all requests.
It now uses the native NodeJS APIs again.
Fixes https://github.com/SAP/ui5-server/issues/183 .
=> [FIX] Makes CSP middleware work in an environment without express server

lib/middleware/csp.js, lib/middleware/nonReadRequests.js, lib/middleware/serveIndex.js, lib/middleware/serveResources.js, lib/middleware/serveThemes.js, package.json, test/lib/server/middleware/nonReadRequests.js, test/lib/server/middleware/serveIndex.js
This makes all middlewares independent of the express specific
`req.path` property by manually parsing the standard `req.url`.
The `parseurl` library is also used within express and makes sure to
not parse the same URL of a request object again by using a cache on
the request object.
Follow up of https://github.com/SAP/ui5-server/pull/184
Fixes: https://github.com/SAP/karma-ui5/issues/64
=> [FIX] Middleware: Allow usage without express server

test/lib/server/middleware/serveIndex.js
See https://github.com/SAP/ui5-fs/pull/140
The tmp directory might not be present during the execution of this
test. However, its usage didn't really add any value to the test
anyways.
=> [INTERNAL] Adapt tests to new behavior of FileSystem._runGlob which now throws for GLOB errors

package-lock.json, package.json, test/lib/server/acceptRemoteConnections.js, test/lib/server/h2.js, test/lib/server/main.js, test/lib/server/middleware/csp.js, test/lib/server/middleware/nonReadRequests.js, test/lib/server/middleware/serveIndex.js, test/lib/server/ports.js, test/lib/server/sslUtil.js
Relevant changelogs:
https://github.com/avajs/ava/releases/tag/v1.0.1
https://github.com/avajs/ava/releases/tag/v2.0.0
Relevant changes:
- AVA now requires at least Node.js 8.9.4. We require only 8.5.
However, since this is a devDependency I guess we can live with that.
- t.throws() does not accept promises anymore. Use t.throwsAsync()
- Test titles now must be unique
=> [INTERNAL] Bump ava to 2.0.0

README.md, index.js, lib/middleware/MiddlewareManager.js, lib/middleware/connectUi5Proxy.js, lib/middleware/discovery.js, lib/middleware/middlewareRepository.js, lib/middleware/serveIndex.js, lib/middleware/serveResources.js, lib/middleware/serveThemes.js, lib/middleware/versionInfo.js, lib/server.js, test/lib/indexLegacyExport.js, test/lib/server/middleware/MiddlewareManager.js, test/lib/server/middleware/middlewareRepository.js, test/lib/server/middleware/serveIndex.js
As per RFC 0005: https://github.com/SAP/ui5-tooling/pull/151
=> [FEATURE] Server: Add handling for custom middleware

lib/middleware/discovery.js, lib/server.js, test/lib/server/middleware/middlewareRepository.js
=> [INTERNAL] Typos fix

lib/middleware/MiddlewareManager.js, lib/middleware/serveIndex.js, lib/middleware/serveResources.js, test/lib/server/main.js, test/lib/server/middleware/serveIndex.js, test/lib/server/middleware/serveResources.js
serveResources uses stringEscaper to escape .properties files.
Builds on [@ui5/builder#293](https://github.com/SAP/ui5-builder/pull/293)
In order to make the tests work [@ui5/builder#293](https://github.com/SAP/ui5-builder/pull/293) needs to be linked into the project.
=> [FEATURE] Properties File Escaping

lib/middleware/MiddlewareManager.js, lib/middleware/serveResources.js, test/lib/server/middleware/serveResources.js
Use propertiesFileSourceEncoding configuration of the project the
resource is originating from instead of the current root project.
=> [INTERNAL] Properties File Escaping follow up

lib/sslUtil.js, package-lock.json, package.json, test/lib/server/sslUtil.js
The "prompt" module comes with several dependencies and has features
which are not required here.
Therefore the "yesno" module is more suitable as it adresses exactly our
use case and has no further npm dependencies.
Closes: https://github.com/SAP/ui5-server/issues/37
=> [INTERNAL] sslUtil: Use "yesno" instead of "prompt" module

lib/middleware/MiddlewareManager.js, test/lib/server/middleware/MiddlewareManager.js
Similar to the implementation for custom tasks:
https://github.com/SAP/ui5-builder/blob/d60c67dafc6d96a8345da2004972cd4b839eece6/lib/types/AbstractBuilder.js#L81-L89
Resolves #222
=> [FEATURE] Custom Middleware Extensibility: Allow multiple definitions of the same custom middleware

lib/middleware/MiddlewareManager.js, lib/middleware/serveIndex.js, lib/middleware/serveIndex/serveIndex.js, lib/server.js, test/lib/server/main.js, test/lib/server/middleware/serveIndex.js
In the last PR (#253) i forgot to expose the cli-arguments to the serveIndex Middleware.
Here is the solution ...
=> [INTERNAL] server: Expose serveIndex options

lib/sslUtil.js, package-lock.json, package.json, test/lib/server/sslUtil.js
Caused by (incorrect) regex introduced in
https://github.com/guybedford/devcert/commit/571f4e6d077f7f21c6aed655ae380d85a7a5d3b8
and released as patch.
Resolved by pin devcert-sanscache dependency to last working version
0.4.6
=> [FIX] sslUtils: Fix Invalid Common Name error

package.json
=> [FIX] serveIndex: Add missing dependency to "graceful-fs"

lib/middleware/serveResources.js, test/lib/server/middleware/serveResources.js
The stream encoding needs to be set in order to properly handle
multi-byte utf8 characters that are split between different chunks.
See:
https://nodejs.org/api/stream.html#stream_readable_setencoding_encoding
=> [FIX] Ensure proper handling of multi-byte characters in streams

lib/middleware/serveResources.js, lib/middleware/serveThemes.js, lib/mime-util.js, package-lock.json, package.json, test/lib/server/main.js, test/lib/server/middleware/serveThemes.js
=> [FEATURE] Enable CSS Variables

lib/middleware/versionInfo.js
To generate the VersionInfo, the used glob pattern should only match .library files within the resource folder. Otherwise it is possible to find additional .library files, e.g. from unit tests.
=> [FIX] versionInfo: Fix pattern to glob for .library files

.eslintignore, lib/middleware/MiddlewareManager.js, lib/middleware/middlewareRepository.js, lib/middleware/testRunner.js, lib/middleware/testRunner/TestRunner.js, lib/middleware/testRunner/testrunner.css, lib/middleware/testRunner/testrunner.html, package.json, test/lib/server/middleware/MiddlewareManager.js, test/lib/server/middleware/testRunner.js
Static resources are copied over from OpenUI5.
Should we add this to our LICENSE.txt? 🤔
=> [FEATURE] Add test runner middleware

lib/middleware/serveResources.js, test/lib/server/middleware/serveResources.js
Also fix some tests that expected different unicode escape sequences
for the same input. The used input encoding did not match the specified
propertiesFileSourceEncoding.
BREAKING CHANGE:
If the project a "*.properties" resource originates from cannot be
determined, or if the project does not define a
propertiesFileSourceEncoding configuration or uses a legacy specVersion
(<2.0), the serveResources middleware assumes that the resource is UTF-8
encoded instead of ISO-8859-1.
=> [BREAKING] serveResources middleware: Expect *.properties files in UTF-8 by default

lib/middleware/csp.js, test/lib/server/middleware/csp.js
Using getHeader/setHeader instead of the express methods get/set to
allow using the middleware with a different server framework or as a
native Node.js server handler.
This also aligns the code with the other middleware which already use
getHeader/setHeader.
=> [FIX] CSP Middleware: Use native res.getHeader/setHeader methods

lib/server.js, test/lib/server/ports.js
This makes it easier for consuming tools to programatically identify
this error.
See also https://nodejs.org/api/errors.html#errors_common_system_errors
=> Server: If port is taken, include "EADDRINUSE" in error message

test/lib/server/middleware/serveIndex.js, test/lib/server/middleware/serveResources.js
Fix ui5-server tests in combination which broke with https://github.com/SAP/ui5-fs/issues/235
Adjust stubs such that they operate on the cloned
resource instead of the original.
* serveIndex: instead of stubbing directly pass the statInfo object such that it gets cloned
* serveResources: ensure the "right" resources are returned by the `byPath` lookup
Fixes: https://github.com/SAP/ui5-fs/issues/250
=> [INTERNAL] serve tests fix: fs Resource#clone change

index.js, jsdoc-plugin.js, jsdoc.json
Lazy-loading breaks the automatic type definition detection from
TypeScript. Therefore we need to manually declare the exported types.
=> [FIX] TypeScript type definition support

lib/middleware/MiddlewareManager.js, lib/middleware/MiddlewareUtil.js, test/lib/server/middleware/MiddlewareUtil.js
New specVersion does not affect MiddlewareUtil but still needs to be
supported and handled.
=> [INTERNAL] MiddlewareUtil: Support specVersion 2.2

lib/middleware/discovery.js
When a library's name is a prefix of another library's name (like with
sap.m and sap.me), the discovery service mistakenly assigned test pages
to both libraries.
By including the slash in the prefix check, only full segment matches
will be taken into account.
By checking the prefixes from longest to shortest and by aborting after
the first match, non-prefix-free lib names can be handled properly. The
longest matching prefix will win and there won't be double assignments.
=> [FIX] Discovery middleware shouldn't fail when lib names overlap

test/lib/server/middleware/serveResources.js
Add resource#getPathTree to mocks used in test.
=> [INTERNAL] test/serveResources: add missing mock methods

lib/middleware/MiddlewareManager.js, lib/middleware/MiddlewareUtil.js, test/lib/server/middleware/MiddlewareUtil.js
New specVersion does not affect MiddlewareUtil but still needs to be
supported and handled.
=> [INTERNAL] MiddlewareUtil: Support specVersion 2.3

.github/workflows/codeql-analysis.yml, .github/workflows/github-ci.yml, .github/workflows/reuse-compliance.yml
In the main branch only workflow configurations related to the main branch are stored.
Other release branches will contain their own configuration.
**Exceptions**: 
- `dependabot.yml`: All branches triggering dependabot updates have to be maintained in the default branch "main" configuration
- `azure-pipelines.yml`: All branches triggering azure pipeline flows have to be maintained in the default branch "main" configuration.
=> [INTERNAL] Remove other than main branch workflows

lib/middleware/serveResources.js, package-lock.json, package.json, test/lib/server/middleware/serveResources.js
Dependency was already removed from UI5 CLI and tracing will be
re-worked anyways. This serves too-little purpose.
=> [INTERNAL] serveResources: Remove treeify dependency

lib/middleware/MiddlewareManager.js, lib/middleware/MiddlewareUtil.js, lib/middleware/serveResources.js, lib/server.js, test/lib/server/middleware/MiddlewareManager.js, test/lib/server/middleware/MiddlewareUtil.js, test/lib/server/middleware/serveIndex.js, test/lib/server/middleware/serveResources.js, test/lib/server/middleware/serveThemes.js
New API is only available to custom middleware defining specVerson 3.0 and later.
Based on [RFC 0012 UI5 Tooling Extension API v3](https://github.com/SAP/ui5-tooling/pull/664)
Depends on https://github.com/SAP/ui5-project/pull/431
=> [FEATURE] MiddlewareUtil: Add getProject/getDependencies/resourceFactory API to interface

lib/middleware/MiddlewareUtil.js, test/lib/server/middleware/MiddlewareUtil.js
Follow-up of https://github.com/SAP/ui5-server/pull/547 where this method was somehow missed
=> [INTERNAL] MiddlewareUtil: Provide resourceFactory#createReaderCollection

lib/middleware/MiddlewareManager.js, test/lib/server/middleware/MiddlewareManager.js
If a middleware with the same name has been configured multiple times,
a suffix will be added to the name. The resulting name should then be
passed to the middleware function.
=> [INTERNAL] MiddlewareManager: Provide correct middlewareName to custom middleware

lib/sslUtil.js, package-lock.json, package.json, test/lib/server/sslUtil.js
The recursive option is available since Node v10.12, which makes the
use of thirdparty packages obsolete for most use cases.
=> [INTERNAL] Use native fs.mkdir instead of make-dir

lib/middleware/MiddlewareUtil.js, test/lib/server/middleware/MiddlewareUtil.js
For custom middleware this will returned a Specification
Version-dependent (=compatible) interface of the Project instance a
Resource is associated with.
This was already described in RFC12[1] but not part of the initial
implementation of MiddlewareUtil#getProject.
[1] https://github.com/SAP/ui5-tooling/pull/664
=> [INTERNAL] MiddlewareUtil#getProject: Retrieve Project for a given Resource

lib/middleware/MiddlewareManager.js, lib/middleware/connectUi5Proxy.js, lib/middleware/middlewareRepository.js, package-lock.json, package.json, test/lib/server/middleware/MiddlewareManager.js
BREAKING CHANGE:
This removes the "/proxy" endpoint and the corresponding
"connectUi5Proxy" middleware from the standard ui5-server.
Internally, this middleware made use of the connect-openui5 proxy
implementation (https://github.com/SAP/connect-openui5#proxy).
More sophisticated proxy solutions for ui5-server are already available
in the form of custom middleware extensions from the UI5-community.
The UI5 Team might provide a dedicated custom middleware extension,
with similar functionality, in the future.
JIRA: CPOUI5FOUNDATION-598
=> [BREAKING] Remove "/proxy" endpoint

lib/middleware/MiddlewareManager.js, lib/middleware/serveResources.js, test/lib/server/middleware/MiddlewareManager.js
Use template literals instead of placeholders.
This is in prepration for @ui5/logger changes as per
https://github.com/SAP/ui5-logger/pull/353
=> [INTERNAL] Refactor log-calls

lib/middleware/MiddlewareManager.js, test/lib/server/middleware/MiddlewareManager.js
Throw an error if the referenced custom middleware can't be found in the project graph. Before, this lead to an obscure `Cannot read properties of undefined (reading 'getSpecVersion')` error
=> [FIX] MiddlewareManager: Throw if custom middleware is unknown

lib/middleware/MiddlewareUtil.js, test/lib/server/middleware/MiddlewareUtil.js
This was missed to add to the initial 3.0.0 release.
Also see https://github.com/SAP/ui5-project/pull/580
Additionally, for the Project#getReader function, default the 'style'
parameter to 'runtime'. We expect this match best with custom middleware
expectations, since ui5-server itself uses the same style.
=> [FIX] MiddlewareUtil: Provide framework configuration getters to custom tasks

lib/middleware/serveResources.js, test/lib/server/middleware/serveResources.js
Fixes: https://github.com/SAP/ui5-tooling/issues/800
=> [FIX] Allow serving of propertyfiles of non component project types

lib/sslUtil.js
BREAKING CHANGE:
Messages will now be written to stderr instead of stdout.
JIRA: CPOUI5FOUNDATION-802
Related to: https://github.com/SAP/ui5-tooling/issues/701
Sibling of: https://github.com/SAP/ui5-tooling/pull/930, https://github.com/SAP/ui5-cli/pull/686
=> [BREAKING] Replace console.log with process.stderr 

lib/middleware/MiddlewareManager.js, lib/middleware/helper/generateLibraryManifest.js, lib/middleware/serveResources.js, lib/middleware/versionInfo.js, test/lib/server/middleware/helper/generateLibraryManifest.js, test/lib/server/middleware/serveResources.js, test/lib/server/middleware/versionInfo.js
UI5 libraries (especially framework libraries) often lack a manifest.json in their source. However some UI5 runtime API requires a manifest.json to function properly. For example to locate i18n resources at a non-default location.
With this change, the serveResources middleware will attempt to generate  missing manifest.json files on-the-fly. This mimics the behavior of the ui5-builder's generateLibraryManifest task and the result is almost identical.
JIRA: CPOUI5FOUNDATION-688
=> [FEATURE] serveResources: Dynamically generate missing library manifest.json

lib/middleware/helper/generateLibraryManifest.js, lib/middleware/serveResources.js, lib/middleware/versionInfo.js, test/lib/server/middleware/serveResources.js, test/lib/server/middleware/versionInfo.js
Ignore any other project types, even if the project contains a .library
file.
Some projects might consume UI5 libraries configured as type "module".
In order to align the ui5-server's behavior with the ui5-builder, those
projects must be ignored when generating the sap-ui-version.json.
For the same reason the serveResources middleware must not attempt to
generate a missing manifest.json for such projects.
(cherry picked from commit f0283ed7b20eff73516d354017233d9b57cf5535)
=> [INTERNAL] middleware/versionInfo: Only process dependencies of type 'library'

lib/middleware/serveResources.js, test/lib/server/middleware/serveResources.js
JIRA: CPOUI5FOUNDATION-296
Depends on:
- https://github.com/SAP/ui5-builder/pull/957
- https://github.com/SAP/ui5-project/pull/683
=> [FEATURE] manifest.json: Auto-fill supportedLocales

package-lock.json, package.json
Upgrade to latest [devcert-sanscache](https://www.npmjs.com/package/devcert-sanscache) version to get rid of deprecated transient dependencies.
Fixes https://github.com/SAP/ui5-tooling/issues/980
JIRA: CPOUI5FOUNDATION-864
=> [DEPENDENCY] Bump devcert-sanscache from 0.4.8 to 5.0.1

lib/middleware/serveResources.js, test/lib/server/middleware/serveResources.js
The middleware is supposed to be in sync with the behavior of the build.
During the build, only manifest.json files within `/resources/` are
processed, so the server must not process files from `/test-resources/`.
A check for `/resources/` would not be correct, as the pathname is based
on the 'runtime'-style, so for applications the path might just be
`/manifest.json`.
=> [FIX] serveResources: Do not process manifest.json in test-resources

lib/sslUtil.js
SSL certificate and key used for the local development server
(restricted to 'localhost' domain) are currently created with
standard file permissions.
This fix ensures '400' permission (only readable and only readable by
owner) when the files are created and also updates any existing files
with incorrect permissions.
=> [FIX] Ensure SSL credentials are only readable by owner

lib/server.js, test/lib/server/h2.js
=> [FIX][V3] Log error in case UI5 Server uses HTTP/2 with Node 24
